# Generated by Django 4.2.10 on 2024-02-19 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('lon', models.DecimalField(decimal_places=16, max_digits=22)),
                ('distance', models.DecimalField(decimal_places=1, max_digits=5)),
                ('date', models.DateField()),
                ('people', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
                ('trip_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trips.triptype')),
            ],
        ),
    ]
