# Generated by Django 4.2.10 on 2024-02-21 01:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0002_alter_trip_date_alter_trip_distance_alter_trip_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='people',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
