# Generated by Django 5.0.3 on 2024-03-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='lon',
        ),
        migrations.AddField(
            model_name='trip',
            name='location',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
